---
title: "Introduction to Probabilistic Machine Learning with RStan"
author: "Daniel Emaasit"
date: "March 31, 2017"
output: 
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
suppressPackageStartupMessages(library(dplyr))
```

# Introduction to Probabilistic Machine Learning with Stan

## Event Information

<https://www.meetup.com/Las-Vegas-R-Users-Group/events/237505653/>

<https://www.meetup.com/Data-Science-Las-Vegas/events/237505738/>


Date: April 27, 2017  

Place: Las Vegas, NV @ InNEVation  

Speaker: Daniel Emaasit  


## Content

* [Slides HTML](https://github.com/Emaasit/meetups/blob/master/2017_04_27_Intro_to_PML_LV/slides/slides.html)
* [Slides PDF](https://github.com/Emaasit/meetups/blob/master/2017_04_27_Intro_to_PML_LV/slides/slides.pdf)  
* [Code R](https://github.com/Emaasit/meetups/blob/master/2017_04_27_Intro_to_PML_LV/intro-to-pml-rstan.Rmd)

## Abstract

Machine Learning has gone mainstream and now powers several real world applications like autonomous vehicles at Uber & Tesla, recommendation engines on Amazon & Netflix, and much more. This meetup will introduce probabilistic machine learning and probabilistic programming with [Stan](http://mc-stan.org/). We will discuss the basics of machine learning from a [probabilistic/Bayesian perspective](http://mlg.eng.cam.ac.uk/zoubin/bayesian.html) and contrast it with traditional/algorithmic machine learning.  

We will also discuss how to build probabilistic models in computer code using a new exciting programming paradigm called [Probabilistic Programming](http://probabilistic-programming.org/wiki/Home) (PP). Particularly we shall use Stan (within R), a PP language, to build models ranging from simple generalized linear models to complex hierarchical models and nonparametric models for machine learning.

## Pre-requisites: 

Please come with a laptop with the following software installed:

* R + RStudio:- Follow this [link](https://www.r-project.org/) to install R. Also install the LATEST version of RStudio.   
* rstan:- Follow this [link](https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Mac-or-Linux) to install rstan on MacOS/Linux or this link for Windows.   
* bayesplot:- Follow this [link](https://github.com/stan-dev/bayesplot) to install bayesplot  

## Speaker Bio: 

[Daniel Emaasit](http://www.danielemaasit.com/) is a PhD student of Transportation Engineering at UNLV. His research interests involve developing [flexible probabilistic/Bayesian machine learning models](http://mlg.eng.cam.ac.uk/pub/topics/#np) for high-dimensional data with applications to urban mobility, travel demand modeling, and highway safety analysis.
